name: Build and Push Docker Image
on:
  push:
    branches: [ "main" ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.sethaguilar }}
          password: ${{ secrets.dckr_pat_aK63q8g-ElVxvLocoJLI1ET_f7M }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.sethaguilar }}/flask-cicd-demo:latest